[build]
  publish = "out" # Change to the static export directory
  command = "next build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Method = ["GET"] } # Ensure POST requests are not redirected
